version: "3.7"
services:
  nginx:
    build: .
    image: michbud98/wireshark_psk:202404
    container_name: wireshark_psk
    restart: always
    ports:
      - '8091:80'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
    name: wireshark

    