version: "3.7"
services:
  nginx:
    build: .
    image: michbud98/wireshark_psk:0.1
    container_name: wireshark_psk
    restart: always
    volumes:
       - type: bind
         source: ./nginx.conf
         target: /etc/nginx/conf.d/default.conf
         read_only: true
    ports:
      - '8091:80'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
    name: wireshark
