version: "3.7"

services:
  nginx:
    build: .
    image: michbud98/crontab.guru-docker:202404
    container_name: crontab-guru
    restart: always
    ports:
      - '8090:80'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
    name: crontab-guru
    