---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - GitHub:
      - abbr: GH
        icon: si-github
        href: https://github.com/
    - Homepage:
      - icon: si-homepage
        href: https://gethomepage.dev/latest/

- Social:
    - Twitter:
      - abbr: TW
        icon: twitter.png
        href: https://twitter.com/

- Entertainment:
    - YouTube:
      - abbr: YT
        icon: youtube.png
        href: https://youtube.com/
    - 1d6chan:
      - abbr: 1d6chan
        icon: mdi-dice-d6-#b042f5
        href: https://1d6chan.miraheze.org/

- News:
    - Seznam:
        - abbr: SZ
          icon: https://seznam.cz/favicon.ico
          href: https://seznam.cz/
    - CeskaTelevize:
        - abbr: CT
          icon: https://ct24.ceskatelevize.cz/static/favicon.ico
          href: https://ct24.ceskatelevize.cz/
