---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Networking:
    - Router:
        href: https://router.home.lan/
        icon: si-mikrotik-#eb7434
        description: A Mikrotik home router
    - Wifi:
        href: https://wifi.home.lan/
        icon: si-openwrt-#34b4eb
        description: An OpenWRT based wifi
    - Technitium DNS:
        href: http://rpi-server.home.lan:5380/
        icon: mdi-dns-#999999
        description: Local DNS server for home network

- Data:
    - RPI NAS:
        href: http://rpi-nas.home.lan/
        icon: si-raspberrypi-#c71441
        description: Open Media Vault NAS running on RPI
    - Home NAS:
        href: http://nas.home.lan/
        icon: si-openmediavault-#5DACDF
        description: Home NAS running on a custom built server

- Infrastructure Management:
    - Portainer:
        href: https://rpi-server.home.lan:9443/
        icon: si-portainer-#13BEF9
        description: Portainer for managing multiple Docker devices.
    - Proxmox:
        href: https://proxmox.home.lan:8006/
        icon: si-proxmox-#E57000
        description: Proxmox server for running virtualized Infrastructure.

- IoT and Smarthome:
    - Grafana:
        href: http://rpi-server.home.lan:3000/
        icon: si-grafana-#F46800
        description: Grafana
    - Nodered:
        href: http://rpi-server.home.lan:1880/
        icon: si-nodered-#8F0000
    - EspHome:
        href: http://rpi-server.home.lan:6052/
        icon: si-esphome-#000000
    - Octoprint:
        href: http://octopi.home.lan/
        icon: si-octoprint-#13C100
        widget:
          type: octoprint
          url: http://octopi.home.lan/
          key: 952EB4B52B814E969415EF9535C77C78

- Miscellaneous:
    - ASCII Generator:
        href: http://rpi-server.home.lan:8092/
        icon: mdi-alpha-a-#a83232
        description: Grafana
    - Crontab Guru:
        href: http://rpi-server.home.lan:8090/
        icon: mdi-alpha-c-#32a852
        description: Grafana
    - Wireshark PSK Generator:
        href: http://rpi-server.home.lan:8091/
        icon: si-wireshark-#1679A7
        description: Grafana
