---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

# - resources:
#     label: System
#     cpu: true
#     memory: false
#     disk: /
#     cputemp: true
#     uptime: true
#     units: celsius # only used by cpu temp
#     refresh: 3000 # optional, in ms
#     diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk

- search:
    provider: duckduckgo
    target: _blank
