version: "3.6"
services:
  nginx:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nginx-countdown
    image: michbud98/nginx-countdown
    volumes:
        - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "8092:80"
